#cloud-config
package_update: true
package_upgrade: true

packages:
  - zsh
  - tmux
  - stow
  - git
  - fzf
  - ninja-build
  - gettext
  - cmake
  - curl
  - wget
  - build-essential
  - libreadline-dev
  - unzip
  - ripgrep
  - zoxide
  - pkg-config
  - libssl-dev
  - g++
  - automake
  - autoconf
  - libtool
  - libtool-bin
  - gnupg2

# 创建一个用户并设置 shell
users:
  - name: akiwu
    shell: /usr/bin/zsh
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    # 可选: 添加 SSH 密钥
    # ssh_authorized_keys:
    #  - ssh-rsa AAA...

runcmd:
  # 为所有用户安装 Zimfw
  - su - akiwu -c "curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh"
  - su - akiwu -c "echo 'skip_global_compinit=1' >> /home/akiwu/.zshrc"
  
  # 配置 zim-zoxide 模块
  - su - akiwu -c "echo 'zmodule kiesman99/zim-zoxide' >> /home/akiwu/.zimrc"
  - su - akiwu -c "zsh -c 'source /home/akiwu/.zshrc && zimfw install'"

  # RVM
  - su - akiwu -c "gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
  - su - akiwu -c "curl -sSL https://get.rvm.io | bash -s master --ruby"
  
  # 安装 Lua 5.1 for Neovim
  - su - akiwu -c "curl -L -R -O http://www.lua.org/ftp/lua-5.1.5.tar.gz"
  - su - akiwu -c "tar zxf lua-5.1.5.tar.gz"
  - su - akiwu -c "cd lua-5.1.5 && make linux test"
  - make -C /home/akiwu/lua-5.1.5 install
  - rm -rf /home/akiwu/lua-5.1.5* # clear
  
  
  # 安装 LuaRocks
  - su - akiwu -c "curl -L -R -O https://luarocks.github.io/luarocks/releases/luarocks-3.9.0.tar.gz"
  - su - akiwu -c "tar zxf luarocks-3.9.0.tar.gz"
  - su - akiwu -c "cd luarocks-3.9.0 && ./configure"
  - make -C /home/akiwu/luarocks-3.9.0 install
  - rm -rf /home/akiwu/luarocks-3.9.0* # clear
  
  # 安装 Neovim from source
  - su - akiwu -c "git clone https://github.com/neovim/neovim.git"
  - make -C /home/akiwu/neovim CMAKE_BUILD_TYPE=Release
  - make -C /home/akiwu/neovim install
  - rm -rf /home/akiwu/neovim # clear
  
  # 初始化 zoxide
  - su - akiwu -c 'echo "eval \"\$(zoxide init zsh)\"" >> /home/akiwu/.zshrc'

  # Nodejs
  - su - akiwu -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash "
  - su - akiwu -c "source '/home/akiwu/.nvm/nvm.sh' && nvm install 22"

  # Install rustup
  - su - akiwu -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  - su - akiwu -c '. "/home/akiwu/.cargo/env" && rustup default stable'

  # Install Zig
  - su - akiwu -c "wget https://ziglang.org/download/0.14.0/zig-linux-aarch64-0.14.0.tar.xz"
  - su - akiwu -c "tar xvf zig-linux-aarch64-0.14.0.tar.xz"
  - su - akiwu -c 'echo "export PATH=\"$HOME/zig-linux-aarch64-0.14.0:$PATH\"" >> /home/akiwu/.zshrc'

  # Add env variables and aliases
  - su - akiwu -c 'echo "\n# Env variables and aliases" >> /home/akiwu/.zshrc'
  - su - akiwu -c 'echo "export EDITOR=vi" >> /home/akiwu/.zshrc'
  - su - akiwu -c "echo 'alias vi=nvim' >> /home/akiwu/.zshrc"
  - su - akiwu -c 'echo "alias ll=\"ls -la\"" >> /home/akiwu/.zshrc'
